Runtime Error
Error: ./src/app/page.tsx:214:1
Parsing ecmascript source code failed
  212 |     }
  213 |   }, [serverState, getValues, hasFirstAnalysisCompleted, setIsPanelOpen, analysisResult, isActionPending]);
> 214 | =======
      | ^^^^^^^
  215 |         setIsPanelOpen(true);
  216 |         setHasFirstAnalysisCompleted(true);
  217 |       }

Merge conflict marker encountered.

Call Stack
7

Show 5 ignore-listed frame(s)
<unknown>
error: ./src/app/page.tsx (214:1)
<unknown> (Error:
./src/app/page.tsx (214:1)